name: build and test

on:
  push:
  schedule:
    - cron: '0 8 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container: cypress/browsers:node13.6.0-chrome80-ff72

    strategy:
      matrix:
        node-version: ['>= 13.2']

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm version
    - run: npm ci
    - run: npm run build
    - run: npm test
      env:
        CI: true
        APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
